### ISSUE TITLE
New middleware - Info of the APP

### ISSUE THREAD

**Issue by agorostidi** [van-ibm/watsonworkspace-starter#2]
Hi @dcacy ,

I would like to have an HTML page with the info of the APP, and the shared link to install it.
How do I insert a middleware on the code to do it ?

The express framework/ http server on this code is provided by the module watsonworkspace-bot, and it seems it has a way to have middlewares associated, but I do not understand how to add them..

**Comment by dcacy** [comment]
Here is a sample using the middleware functionality:

```
const customMiddleware = [
  ['servicenow','config'],
  [
    function(req, res) {handleServiceNow.handle(req, res, bot)},
    function(req, res) {handleConfig.config(req, res, bot)}
  ]
];
const bot = botFramework.create(
  process.env.APP_ID,
  process.env.APP_SECRET,
  process.env.WEBHOOK_SECRET,
  customMiddleware[0],
  customMiddleware[1]
); 
```

You need to create two arrays. The first array contains the routes, such as `servicenow` and `config`.  The second array is the function that each route should invoke, such as `function(req, res) {handleServiceNow.handle(req, res, bot)`.  The order of the items in the array is important; if the framework finds a route in the first element of the first array, it will invoke the function in the first element of the second array.

The framework currently doesn't have much to help you with the config itself. There is a `getConfigurationData` function on the sdk as a start.
